import Head from 'next/head';

export default function HeadComponent() {
  return (
    <Head>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <meta name="description" content="Generated by create next app" />
      <link rel="preconnect" href="https://fonts.gstatic.com" />
      <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@400;500;700&display=swap" rel="stylesheet" />
      <link rel="icon" href="/favicon.svg" />
      <title>movie-tv</title>
    </Head>
  );
}
